apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secret.yaml
  - rbac.yaml
  - postgres.yaml
  - redis.yaml
  - minio.yaml
  - migrate-job.yaml
  - retention-cronjob.yaml
  - api.yaml
  - worker.yaml
  - sender.yaml
  - finalizer.yaml
